### ISSUE TITLE
How to get gyroscope readings in radians/sec ?

### ISSUE THREAD

**Issue by saltrack** [DFRobot/DFRobot_BMX160#5]
I have evaluated the gyroscope readings from DFR module using arduino which specifies that the gyroscope data is in g

What is g here?

**Comment by LongToeBoy** [comment]
g is gravity. 9.8 m/s², reading is normalized according to gravity on earth. gyroscope readings are angular acceleration so radian/sec is incorrect unit. i think you're approaching problem the wrong way. what exactly are you trying to do?

**Comment by saltrack** [comment]
Thank you for a quick reply. I was trying to understand what g is in this line : https://github.com/DFRobot/DFRobot_BMX160/blob/700c38518e23cfd97326a8899e3491167bb18212/examples/readGyroData/readGyroData.ino#L47

The gyroscope data doesn't seem to be in rad/sec, I've compared it with other gyroscope mounted on the same system and there is orders of magnitude difference in the readings.

Any help would be greatly appreciated.

**Comment by saltrack** [comment]
FYI : https://learn.sparkfun.com/tutorials/gyroscope/all

**Comment by saltrack** [comment]
Are you saying that the BMX160 gyro gives angular acceleration data ?

**Comment by Vic-Y** [comment]
Hi,

The BMX160 datasheet says the output should be in degrees per second (dps).  This would also be consistent with the enum comments above setGyroRange in line 35:
https://github.com/DFRobot/DFRobot_BMX160/blob/700c38518e23cfd97326a8899e3491167bb18212/examples/readGyroData/readGyroData.ino#L27-L35

If you convert 360 dps = 2 * pi radians/sec, would this make the output agree with your other gyroscope?

If yes, then change line 47 and line 52 from "g" to "dps".
